[build]
  publish = "build/web"
  command = """
    if cd flutter; then \
      git pull && cd ..; \
    else \
      git clone https://github.com/flutter/flutter.git -b 3.24.0 --depth 1; \
    fi && \
    export PATH="$PATH:`pwd`/flutter/bin" && \
    flutter doctor && \
    flutter clean && \
    flutter config --enable-web && \
    flutter pub get && \
    flutter build web --release
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
